# Generated by Django 4.1.7 on 2024-03-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя_Клиента')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('message', models.CharField(max_length=500, verbose_name='Текст_сообщения')),
                ('state', models.BooleanField(default=False, verbose_name='Статус сообщения')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
