# Generated by Django 4.1.7 on 2024-03-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Clients',
        ),
    ]
